### ISSUE TITLE
File not found: nucypher_core_wasm_bg.wasm when building a Next.js app

### ISSUE THREAD

**Issue by manumonti** [nucypher/nucypher-ts#259]
I'm trying to build a simple demo app from scratch using Next.js. This is the current status:

https://github.com/manumonti/nucypher-ts-simple-demo/commit/ce8a2e1e564b2d23b7da2c908c63ea3823833d26

When trying to import nucypher-ts, I get the following error:

```
Error: ENOENT: no such file or directory, open '/Users/manumonti/Projects/manumonti/nucypher-ts-simple-demo/.next/server/app/nucypher_core_wasm_bg.wasm'
```

(To reproduce, just run `$ npm dev`)

Also, I get some `Module not found` warnings. This is the complete trace:

```
nucypher-ts-simple-demo@0.1.0 dev
> next dev

- ready started server on 0.0.0.0:3000, url: http://localhost:3000
- event compiled client and server successfully in 249 ms (20 modules)
- wait compiling...
- event compiled client and server successfully in 70 ms (20 modules)
- wait compiling /page (client and server)...
- warn ./node_modules/ws/lib/buffer-util.js
Module not found: Can't resolve 'bufferutil' in '/Users/manumonti/Projects/manumonti/nucypher-ts-simple-demo/node_modules/ws/lib'

Import trace for requested module:
./node_modules/ws/lib/buffer-util.js
./node_modules/ws/lib/websocket.js
./node_modules/ws/index.js
./node_modules/@ethersproject/providers/lib/ws.js
./node_modules/@ethersproject/providers/lib/websocket-provider.js
./node_modules/@ethersproject/providers/lib/index.js
./node_modules/ethers/lib/ethers.js
./node_modules/@nucypher/nucypher-ts/build/module/src/conditions/context/providers.js
./node_modules/@nucypher/nucypher-ts/build/module/src/conditions/context/context.js
./node_modules/@nucypher/nucypher-ts/build/module/src/conditions/context/index.js
./node_modules/@nucypher/nucypher-ts/build/module/src/conditions/index.js
./node_modules/@nucypher/nucypher-ts/build/module/src/index.js
./src/app/page.tsx

./node_modules/ws/lib/validation.js
Module not found: Can't resolve 'utf-8-validate' in '/Users/manumonti/Projects/manumonti/nucypher-ts-simple-demo/node_modules/ws/lib'

Import trace for requested module:
./node_modules/ws/lib/validation.js
./node_modules/ws/lib/receiver.js
./node_modules/ws/index.js
./node_modules/@ethersproject/providers/lib/ws.js
./node_modules/@ethersproject/providers/lib/websocket-provider.js
./node_modules/@ethersproject/providers/lib/index.js
./node_modules/ethers/lib/ethers.js
./node_modules/@nucypher/nucypher-ts/build/module/src/conditions/context/providers.js
./node_modules/@nucypher/nucypher-ts/build/module/src/conditions/context/context.js
./node_modules/@nucypher/nucypher-ts/build/module/src/conditions/context/index.js
./node_modules/@nucypher/nucypher-ts/build/module/src/conditions/index.js
./node_modules/@nucypher/nucypher-ts/build/module/src/index.js
./src/app/page.tsx
- error Error: ENOENT: no such file or directory, open '/Users/manumonti/Projects/manumonti/nucypher-ts-simple-demo/.next/server/app/nucypher_core_wasm_bg.wasm'
    at Object.openSync (node:fs:600:3)
    at Object.readFileSync (node:fs:468:35)
    at __webpack_require__ (/Users/manumonti/Projects/manumonti/nucypher-ts-simple-demo/.next/server/webpack-runtime.js:33:43)
    at __webpack_require__ (/Users/manumonti/Projects/manumonti/nucypher-ts-simple-demo/.next/server/webpack-runtime.js:33:43)
    at __webpack_require__ (/Users/manumonti/Projects/manumonti/nucypher-ts-simple-demo/.next/server/webpack-runtime.js:33:43)
    at __webpack_require__ (/Users/manumonti/Projects/manumonti/nucypher-ts-simple-demo/.next/server/webpack-runtime.js:33:43)
    at eval (./src/app/page.tsx:9:79)
    at (ssr)/./src/app/page.tsx (/Users/manumonti/Projects/manumonti/nucypher-ts-simple-demo/.next/server/app/page.js:5378:1)
    at __webpack_require__ (/Users/manumonti/Projects/manumonti/nucypher-ts-simple-demo/.next/server/webpack-runtime.js:33:43)
- warn ./node_modules/ws/lib/buffer-util.js
Module not found: Can't resolve 'bufferutil' in '/Users/manumonti/Projects/manumonti/nucypher-ts-simple-demo/node_modules/ws/lib'

Import trace for requested module:
./node_modules/ws/lib/buffer-util.js
./node_modules/ws/lib/websocket.js
./node_modules/ws/index.js
./node_modules/@ethersproject/providers/lib/ws.js
./node_modules/@ethersproject/providers/lib/websocket-provider.js
./node_modules/@ethersproject/providers/lib/index.js
./node_modules/ethers/lib/ethers.js
./node_modules/@nucypher/nucypher-ts/build/module/src/conditions/context/providers.js
./node_modules/@nucypher/nucypher-ts/build/module/src/conditions/context/context.js
./node_modules/@nucypher/nucypher-ts/build/module/src/conditions/context/index.js
./node_modules/@nucypher/nucypher-ts/build/module/src/conditions/index.js
./node_modules/@nucypher/nucypher-ts/build/module/src/index.js
./src/app/page.tsx

./node_modules/ws/lib/validation.js
Module not found: Can't resolve 'utf-8-validate' in '/Users/manumonti/Projects/manumonti/nucypher-ts-simple-demo/node_modules/ws/lib'

Import trace for requested module:
./node_modules/ws/lib/validation.js
./node_modules/ws/lib/receiver.js
./node_modules/ws/index.js
./node_modules/@ethersproject/providers/lib/ws.js
./node_modules/@ethersproject/providers/lib/websocket-provider.js
./node_modules/@ethersproject/providers/lib/index.js
./node_modules/ethers/lib/ethers.js
./node_modules/@nucypher/nucypher-ts/build/module/src/conditions/context/providers.js
./node_modules/@nucypher/nucypher-ts/build/module/src/conditions/context/context.js
./node_modules/@nucypher/nucypher-ts/build/module/src/conditions/context/index.js
./node_modules/@nucypher/nucypher-ts/build/module/src/conditions/index.js
./node_modules/@nucypher/nucypher-ts/build/module/src/index.js
./src/app/page.tsx
- wait compiling /favicon.ico/route (client and server)...
- warn ./node_modules/ws/lib/buffer-util.js
Module not found: Can't resolve 'bufferutil' in '/Users/manumonti/Projects/manumonti/nucypher-ts-simple-demo/node_modules/ws/lib'

Import trace for requested module:
./node_modules/ws/lib/buffer-util.js
./node_modules/ws/lib/websocket.js
./node_modules/ws/index.js
./node_modules/@ethersproject/providers/lib/ws.js
./node_modules/@ethersproject/providers/lib/websocket-provider.js
./node_modules/@ethersproject/providers/lib/index.js
./node_modules/ethers/lib/ethers.js
./node_modules/@nucypher/nucypher-ts/build/module/src/conditions/context/providers.js
./node_modules/@nucypher/nucypher-ts/build/module/src/conditions/context/context.js
./node_modules/@nucypher/nucypher-ts/build/module/src/conditions/context/index.js
./node_modules/@nucypher/nucypher-ts/build/module/src/conditions/index.js
./node_modules/@nucypher/nucypher-ts/build/module/src/index.js
./src/app/page.tsx

./node_modules/ws/lib/validation.js
Module not found: Can't resolve 'utf-8-validate' in '/Users/manumonti/Projects/manumonti/nucypher-ts-simple-demo/node_modules/ws/lib'

Import trace for requested module:
./node_modules/ws/lib/validation.js
./node_modules/ws/lib/receiver.js
./node_modules/ws/index.js
./node_modules/@ethersproject/providers/lib/ws.js
./node_modules/@ethersproject/providers/lib/websocket-provider.js
./node_modules/@ethersproject/providers/lib/index.js
./node_modules/ethers/lib/ethers.js
./node_modules/@nucypher/nucypher-ts/build/module/src/conditions/context/providers.js
./node_modules/@nucypher/nucypher-ts/build/module/src/conditions/context/context.js
./node_modules/@nucypher/nucypher-ts/build/module/src/conditions/context/index.js
./node_modules/@nucypher/nucypher-ts/build/module/src/conditions/index.js
./node_modules/@nucypher/nucypher-ts/build/module/src/index.js
./src/app/page.tsx
- warn Fast Refresh had to perform a full reload due to a runtime error.
- error Error: ENOENT: no such file or directory, open '/Users/manumonti/Projects/manumonti/nucypher-ts-simple-demo/.next/server/app/nucypher_core_wasm_bg.wasm'
    at Object.openSync (node:fs:600:3)
    at Object.readFileSync (node:fs:468:35)
    at __webpack_require__ (/Users/manumonti/Projects/manumonti/nucypher-ts-simple-demo/.next/server/webpack-runtime.js:33:43)
    at __webpack_require__ (/Users/manumonti/Projects/manumonti/nucypher-ts-simple-demo/.next/server/webpack-runtime.js:33:43)
    at __webpack_require__ (/Users/manumonti/Projects/manumonti/nucypher-ts-simple-demo/.next/server/webpack-runtime.js:33:43)
    at __webpack_require__ (/Users/manumonti/Projects/manumonti/nucypher-ts-simple-demo/.next/server/webpack-runtime.js:33:43)
    at eval (./src/app/page.tsx:9:79)
    at (ssr)/./src/app/page.tsx (/Users/manumonti/Projects/manumonti/nucypher-ts-simple-demo/.next/server/app/page.js:5378:1)
    at __webpack_require__ (/Users/manumonti/Projects/manumonti/nucypher-ts-simple-demo/.next/server/webpack-runtime.js:33:43)
```

I'm using Node.js v18.14.0

**Comment by piotr-roslaniec** [comment]
Closed by #299
